// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mJ-K6jmls9QL6aJRS0gGfCEdlFssEL0',
    appId: '1:648797136615:web:c43530df04cd9fb33fa442',
    messagingSenderId: '648797136615',
    projectId: 'skillocity-fbf61',
    authDomain: 'skillocity-fbf61.firebaseapp.com',
    storageBucket: 'skillocity-fbf61.firebasestorage.app',
    measurementId: 'G-05M56BT2SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvRteYRaVMFw2qORzOzjjril0ROBwlb7s',
    appId: '1:648797136615:android:ea5d67d96b3a8f693fa442',
    messagingSenderId: '648797136615',
    projectId: 'skillocity-fbf61',
    storageBucket: 'skillocity-fbf61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_RQlVBhdzqICPO5Hi7fSdyh4gwzcxQ-c',
    appId: '1:648797136615:ios:79a9787ba61bac143fa442',
    messagingSenderId: '648797136615',
    projectId: 'skillocity-fbf61',
    storageBucket: 'skillocity-fbf61.firebasestorage.app',
    iosBundleId: 'com.example.skillocity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_RQlVBhdzqICPO5Hi7fSdyh4gwzcxQ-c',
    appId: '1:648797136615:ios:79a9787ba61bac143fa442',
    messagingSenderId: '648797136615',
    projectId: 'skillocity-fbf61',
    storageBucket: 'skillocity-fbf61.firebasestorage.app',
    iosBundleId: 'com.example.skillocity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6mJ-K6jmls9QL6aJRS0gGfCEdlFssEL0',
    appId: '1:648797136615:web:38a7f7936ce288753fa442',
    messagingSenderId: '648797136615',
    projectId: 'skillocity-fbf61',
    authDomain: 'skillocity-fbf61.firebaseapp.com',
    storageBucket: 'skillocity-fbf61.firebasestorage.app',
    measurementId: 'G-H4LJVYS9TY',
  );
}
